# Generated by Django 4.0.1 on 2022-07-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mytext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('djtext', models.TextField()),
                ('antxt', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
